version: 2
jobs:
  build:
    working_directory: ~/futtetennismo
    docker:
      - image: futtetennista/hakyll:4.9.8.0
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-stack-work-{{ checksum "magnus108-github-io.cabal" }}
      - run: stack build
      - save_cache:
          paths:
            - ~/magnus108.github.io/.stack-work
            - /root/.stack/
          key: v1-stack-work-{{ checksum "magnus108-github-io.cabal" }}
      - deploy:
          name: Deploy master to Github Pages
          command: |
            git submodule update --init --remote --merge
            stack exec site rebuild
            git config --global user.email circleci@circleci.com
            git config --global user.name CircleCI
            cd _site/
            git checkout master
            git status
            git add --all
            git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
            git push origin master
