version: 2
jobs:
  build:
    working_directory: ~/futtetennismo
    docker:
      - image: futtetennista/hakyll:latest
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - run: stack install
      - run: git submodule init
      - run: git submodule update
      - deploy:
          name: Deploy master to Github Pages
          command: |
            git config --global user.email circleci@circleci.com
            git config --global user.name CircleCI
            cd _site/
            git checkout master
            cd ..
            stack exec site rebuild
            cd _site/
            git status
            git add --all
            git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
            git push origin master
