version: 2
jobs:
  build:
    working_directory: ~/futtetennismo
    docker:
      - image: futtetennista/hakyll:latest
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - run: stack install
      - run: git submodule init
      - run: git submodule update
      - run: cd _site/ && git checkout master
      - run: stack exec site rebuild
      - deploy:
          name: Deploy master to Github Pages
          command: |
            git config --global user.email circleci@circleci.com
            git config --global user.name CircleCI
            cd _site/ && git status
            cd _site/ && git add --all
            cd _site/ && git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
            cd _site/ && git push origin master
